[package]
name = "contract"
version = "0.1.0"
authors = ["Hein Dauven  <heindauven@gmail.com"]
edition = "2021"

[dependencies]
dario_fsm = { path = "../dario_fsm" }
piecrust-macros = { git = "https://github.com/HDauven/piecrust-macros" }
piecrust-uplink = { version = "0.9.0", features = ["abi", "dlmalloc"] }

[lib]
crate-type = ["cdylib", "rlib"]