[package]
name = "contract"
version = "0.1.0"
authors = ["Hein Dauven  <heindauven@gmail.com"]
edition = "2021"

[dependencies]
dario_fsm = { path = "../dario_fsm" }
piecrust-macros = { workspace = true }
piecrust-uplink = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
